



[KeyCodes]
# For a list of keycodes see https://docs.unity3d.com/Manual/class-InputManager.html
RandomizeAllKey = "[1]"
RandomizeFaceKey = "[2]"
RandomizeBodyKey = "[3]"
RandomizeFaceBodyKey = "[4]"
RandomizeClothesKey = "[5]"
# ;SaveCardKey = Keypad6
# ;ExportPresetKey = Keypad7




[FaceSettings]
headId = [0, 4]      #Face types
texFaceId = [0, 26]   #Face types
texFaceDetailId = [0, 9]     
faceDetailWeight = [0.1, 0.8]  #Things like muscles
heterochromia_chance = 10
eye_shadow_chance = 20
cheeks_detail_chance = 20
mole_chance = 10
elf_ears_chance = 10

[BodySettings]
body_detail_chance = 40 #Things like muscles
tattoo_chance = 10
sunburn_chance = 20




[BodyPreset]
[BodyPreset.BodyPreset1]
height = [0.4, 0.8]
bust_size = [0.4, 0.8]
breast_height = [0.4, 0.8]
breast_direction = [0.4, 0.8]
breast_spacing = [0.4, 0.8]
breast_angle = [0.4, 0.8]
breast_lenght = [0.4, 0.8]
areola_puffiness = [0.4, 0.8]
nipple_width = [0.4, 0.8]
head_size = [0.4, 0.8]
neck_width = [0.4, 0.8]
neck_thickness = [0.4, 0.8]
thorax_width = [0.4, 0.8]
thorax_thickness = [0.4, 0.8]
chest_width = [0.4, 0.8]
chest_thickness = [0.4, 0.8]
waist_width = [0.4, 0.8]
waist_thickness = [0.4, 0.8]
waist_height = [0.4, 0.8]
pelvis_width = [0.4, 0.8]
pelvis_thickness = [0.4, 0.8]
hips_width = [0.4, 0.8]
butt = [0.4, 0.8]
butt_angle = [0.4, 0.8]
thighs = [0.4, 0.8]
legs = [0.4, 0.8]
calves = [0.4, 0.8]
ankles = [0.4, 0.8]
shoulders = [0.4, 0.8]
upper_arms = [0.4, 0.8]
lower_arms = [0.4, 0.8]




[FacePreset]
[FacePreset.FacePreset1]
overall_face_breadth = [0.35, 0.45]
upper_face_depth = [0.3, 0.45]
face_height = [0.4, 0.52]
lower_face_depth = [0.45, 0.6]
lower_face_width = [0.1, 0.4]
jaw_width = [0.4, 0.8]  
jaw_height = [0.4, 0.8] 
jaw_depth = [0.4, 0.8]  
jaw_angle = [0.4, 0.8] 
neck_droop = [0.4, 0.8]
chin_width = [0.4, 0.8]
chin_height = [0.4, 0.8]
chin_depth = [0.4, 0.8]
lower_cheek_height = [0.4, 0.8]
lower_cheek_depth = [0.4, 0.8]
lower_cheek_width = [0.4, 0.8]
upper_cheek_height = [0.4, 0.8]
upper_cheek_depth = [0.4, 0.8]
upper_cheek_width = [0.4, 0.8]
eyebrow_height = [0.4, 0.8]
eyebrow_spacing = [0.4, 0.8]
eyebrow_angle = [0.4, 0.8]
inner_arching = [0.4, 0.8]
outer_arching = [0.4, 0.8]
eye_height = [0.4, 0.8]
eye_spacing = [0.4, 0.8]
eye_depth = [0.4, 0.8]
eye_width = [0.4, 0.8]
eye_openness = [0.4, 0.8]
eye_angle_1 = [0.4, 0.8]
eye_angle_2 = [0.4, 0.8]
inner_corner_distance = [0.4, 0.8]
outer_corner_distance = [0.4, 0.8]
inner_corner_height = [0.4, 0.8]
outer_corner_height = [0.4, 0.8]
eyelid_shape_1 = [0.4, 0.8]
eyelid_shape_2 = [0.4, 0.8]
pupil_pos = [0.4, 0.8]
pupil_width = [0.4, 0.8]
pupil_height = [0.4, 0.8]
nose_height = [0.4, 0.8]
nose_projection = [0.4, 0.8]
nose_angle = [0.4, 0.8]
nose_size = [0.4, 0.8]
bridge_height = [0.4, 0.8]
bridge_width = [0.4, 0.8]
bridge_shape = [0.4, 0.8]
nose_width = [0.4, 0.8]
nostril_height = [0.4, 0.8]
nostril_length = [0.4, 0.8]
nostril_inner_width = [0.4, 0.8]
nostril_outer_width = [0.4, 0.8]
tip_height = [0.4, 0.8]
tip_length = [0.4, 0.8]
tip_size = [0.4, 0.8]
mouth_height = [0.4, 0.8]
mouth_width = [0.4, 0.8]
lip_thickness = [0.4, 0.8]
mouth_projection = [0.4, 0.8]
upper_lip thickness = [0.4, 0.8]
lower_lip thickness = [0.4, 0.8]
corner_shape = [0.4, 0.8]
ear_size = [0.4, 0.8]
ear_angle = [0.4, 0.8]
ear_rotation = [0.4, 0.8]
upper_ear shape = [0.4, 0.8]
lower_ear shape = [0.4, 0.8]







